### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Twiitchter** [mw-138/fivem-deferralCards#1]
I personally love this and am having a play around with it at the moment doing dynamic card rendering on criteria being met. Well done!

I was wondering if you plan on putting a license on it, like MIT or such?
If I can get my tests working correctly, I'd love to bundle it into my works rather than using an export or listing as a dependency  that's all.

A-Ok if not too!

**Comment by mw-138** [comment]
Glad to hear you like this project. I just pushed a commit which adds a GNU General Public License so you can use it wherever you like.

**Comment by Twiitchter** [comment]
Much love.
